spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 1800000
      minimum-idle: 5
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/zyxx_shiro?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html

  redis:
    database: 0
    host: 127.0.0.1
    password: ''
    port: 6379
    timeout: 10000ms
    lettuce:
      pool:
        max-idle: 8
        max-wait: 2000ms
        min-idle: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.zyxx.*.entity

zyxx:
  swagger:
    title: 接口文档
    enabled: true
    version: 1.0
    author: tellsea
    url: https://github.com/tellsea
    email: 3210054449@qq.com
    description: 更多项目：https://github.com/tellsea
    terms-of-service-url: https://www.apache.org/licenses/LICENSE-2.0.html
    controller-url: com.zyxx.system.controller
  shiro:
    jwtTokenTimeOut: 3600
    encryptAESKey: V2FuZzkyNuYSKIuwqTQkFQSUpXVA
    encryptJWTKey: U0JBUElOENhspJrzkyNjQ1NA
    # 访问token有效期
    accessTokenExpireTime: 300
    # shiro缓存有效期
    shiroCacheExpireTime: 300
    # 刷新token有效期
    refreshTokenExpireTime: 1800
  aop:
    openLog: true
